# Generated by Django 3.1.3 on 2020-12-11 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20201211_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=100)),
                ('f2', models.EmailField(max_length=254)),
                ('f3', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student1',
            name='contactinfo1_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher1',
            name='contactinfo1_ptr',
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.parent')),
                ('f4', models.IntegerField()),
                ('f5', models.IntegerField()),
            ],
            bases=('testapp.parent',),
        ),
        migrations.DeleteModel(
            name='ContactInfo1',
        ),
        migrations.DeleteModel(
            name='Student1',
        ),
        migrations.DeleteModel(
            name='Teacher1',
        ),
        migrations.CreateModel(
            name='subchild',
            fields=[
                ('child_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.child')),
                ('f6', models.CharField(max_length=100)),
                ('f7', models.IntegerField()),
            ],
            bases=('testapp.child',),
        ),
    ]
